spring:
  datasource:
    drive-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/value_object_db?useTimezone=true&serverTimezone=UTC
    username: root
    password: Admin123#
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
    show-sql: true